### ISSUE TITLE
task.GetList sort_by wrong typing

### ISSUE THREAD

**Issue by jb3662** [pklauke/pycamunda#9] opened 2020-07-16 07:49 UTC
https://github.com/pklauke/pycamunda/blob/7689040b3a0f65c5a0bf65a49a50be444163c7c0/pycamunda/task.py#L236

this is the wrong typing?
should be this
'created': 'created',

**Comment by pklauke** [comment] 2020-07-16 07:58
Hi,

thanks for pointing this out! I will fix this soon.

Regards,
Peter

**Comment by pklauke** [comment] 2020-07-16 15:34
The issue is now fixed in version 0.0.1b4.

**Closed by pklauke** 2020-07-16 15:34 UTC
